package repository

import (
	"context"
	"errors"

	"github.com/simpwf/workflow-engine/internal/workflow/model"
	"github.com/simpwf/workflow-engine/pkg/ids"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// ErrUserNotFound is returned when no user row matches the lookup.
var ErrUserNotFound = errors.New("repository: user not found")

// UpsertSystemUser inserts the configured audit actor, or updates its name,
// email, and metadata if it already exists. It never duplicates.
func UpsertSystemUser(ctx context.Context, db *gorm.DB, u model.User) error {
	return db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var existing UserModel
		err := tx.Where("id = ?", u.ID).First(&existing).Error
		switch {
		case errors.Is(err, gorm.ErrRecordNotFound):
			m := UserToModel(u)
			return tx.Create(&m).Error
		case err != nil:
			return err
		default:
			existing.Name = u.Name
			existing.Email = u.Email
			existing.Metadata = jsonCol(u.Metadata, "{}")
			return tx.Save(&existing).Error
		}
	})
}

// UserRepository resolves an authenticated identity onto a users row.
type UserRepository interface {
	// UpsertBySubject returns the users.id uuid for a provider identity,
	// inserting the row on first sight and refreshing the display name,
	// email, and cached roles metadata on every later request. A caller
	// without a provider identity (the API-token service principal) is
	// never written here: it already has a configured user id.
	UpsertBySubject(ctx context.Context, u model.User) (string, error)
	// GetByID returns one user.
	GetByID(ctx context.Context, id string) (model.User, error)
}

type userRepository struct {
	db *gorm.DB
}

// NewUserRepository builds the user repository.
func NewUserRepository(db *gorm.DB) UserRepository {
	return &userRepository{db: db}
}

// UpsertBySubject resolves (subject, issuer) onto a stable uuid. The uuid is
// generated by the caller so a retry after a failed write produces the same
// id and cannot fork one human into two rows. Roles are cached in metadata
// for debugging only: authorization always reads the live token.
func (r *userRepository) UpsertBySubject(ctx context.Context, u model.User) (string, error) {
	if u.Subject == "" || u.Issuer == "" {
		return "", errors.New("repository: upsert user by subject requires subject and issuer")
	}
	if !ids.Valid(u.ID) {
		return "", errors.New("repository: upsert user by subject requires a valid uuid")
	}
	// The insert and the conflict are resolved by the database in one
	// statement. A select-then-insert reads "no such user" for every
	// concurrent request carrying the same fresh identity, and the losers
	// then race into uq_users_subject_issuer and fail with a duplicate key;
	// this write is just-in-time on the request path, so two requests from
	// one human are routine rather than exotic.
	//
	// uq_users_subject_issuer is partial (WHERE subject <> ''), so the
	// conflict target has to repeat the predicate: without it PostgreSQL
	// rejects the statement outright instead of inferring the index.
	//
	// The id that comes back is the row this call landed on, which is not
	// always the candidate u.ID: on a repeat sighting the existing row
	// keeps its own id, and returning u.ID would hand every
	// created_by/updated_by foreign key an id that matches no user.
	m := UserToModel(u)
	if err := r.db.WithContext(ctx).Clauses(
		clause.OnConflict{
			Columns: []clause.Column{{Name: "subject"}, {Name: "issuer"}},
			// TargetWhere is the index predicate that conflict inference
			// needs. The sibling Where field would land after DO UPDATE SET
			// and constrain the update instead.
			TargetWhere: clause.Where{Exprs: []clause.Expression{clause.Neq{Column: clause.Column{Name: "subject"}, Value: ""}}},
			// The id is deliberately absent: it is the primary key the
			// existing row already owns, and every audit foreign key points
			// at it.
			DoUpdates: clause.AssignmentColumns([]string{"name", "email", "metadata", "updated_at"}),
		},
		// GORM only asks for a column it knows the database filled in, so
		// the id is requested explicitly: on the conflict branch it is the
		// existing row's id, and that is the value this call has to return.
		clause.Returning{Columns: []clause.Column{{Name: "id"}}},
	).Create(&m).Error; err != nil {
		return "", err
	}
	if !ids.Valid(m.ID) {
		return "", errors.New("repository: upsert user by subject landed on no user row")
	}
	return m.ID, nil
}

// GetByID returns one user, mapping a missing row to ErrUserNotFound.
func (r *userRepository) GetByID(ctx context.Context, id string) (model.User, error) {
	if !ids.Valid(id) {
		return model.User{}, ErrUserNotFound
	}
	var m UserModel
	if err := r.db.WithContext(ctx).Where("id = ?", id).First(&m).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return model.User{}, ErrUserNotFound
		}
		return model.User{}, err
	}
	return UserFromModel(m), nil
}
